figure, 
for s = 1:24, 
    subplot(6,4,s), 
    plot(data(s).pop1_gleak_Il,data(s).pop1_iKs_n), 
%     ylim([0 .7]), 
%     xlim([-80 0]), 
    if mod(s, 4) == 1, 
        ylabel({['I_{app} = ', num2str(data(s).pop1_I_app, '%.3g')];'iKs Gating Var.'},'FontSize',14), 
    end, 
    if ceil(s/4) == 6, 
        xlabel('Voltage','FontSize',14), 
    end, 
    if ceil(s/4) == 1, 
        title(['g_{leak} = ', num2str(data(s).pop1_gl, '%.3g')],'FontSize',16), 
    end, 
end